Implement and test file seek, extract common "read_exactly" for reuse
osmcode/libosmium pull request #368
Opened 2023-11-27 01:04 UTC by BenWiederhake

This PR:
- Extracts the private method `osmium::io::detail::PbfParser::read_exactly` as a generic, easily reusable function
- Implements `osmium::util::file_seek` for random access in files (currently unused, see below)
- Tests the seek feature (which also uses `read_exactly`)

This works toward #367, which is where `file_seek` will be very useful.

If you think `file_seek` should instead live in `experimental`, I'd be happy to move the function there.

2023-11-27 02:39 UTC, BenWiederhake commented
Changes since last push:
- Added `#include <cassert>` to read_write.hpp, since I use assert(). Found through iwyu, even though its output is incredibly noisy.

2023-12-01 16:24 UTC, joto requested changes
Looks good, except the two small things I wrote down.

I am getting some weird effects here that github actions seems not to be testing your newsest commit. Hopefully this sorts itself out when you add those changes.

2023-12-01 16:24 UTC, joto commented on include/osmium/util/file.hpp
> +            _lseeki64(fd, offset, SEEK_SET);
We'll need a cast here (and below for the `lseek`) because `off_t` is a signed type and `size_t` is unsigned, to avoid warnings.

2023-12-01 16:24 UTC, joto commented on test/t/io/test_file_seek.cpp
> +        printf("Trying to seek to %lu\n", expect.offset);
Please remove this line, tests should usually not produce output.

2023-12-01 20:49 UTC, BenWiederhake commented
Changes since last push:
- Added the cast to __int64, that seems to be the type that's also used in other MSVC-specific implementations, like resize_file.
- Removed the print from the test

2023-12-03 09:32 UTC, merged